jQuery(function($){$(document).ready(function(){if($('.easysteps-section').length){let module='.easysteps-section';let block_id=$(module).data('block-id');$('#easysteps-modal-'+block_id,$(module)).appendTo("body");let mobile_link_text=$($('.modal-link-placeholder',$(module)).length?$('.modal-link-placeholder',$(module)):$('.button-continue a',$(module))).text();if(mobile_link_text!=''){$('.easysteps-modal-link span',$(module)).text(guSubstituteString(mobile_link_text));}else{$('.easysteps-modal-link span',$(module)).remove();}}
$(document).on('shown.bs.modal','.video-modal',function(e){let videosrc=$('iframe',$(this)).attr('src');if($('iframe',$(this)).attr('data-src')===undefined){videosrc+=(videosrc.indexOf('?')>-1?'&':'?')+'autoplay=1&modestbranding=1&showinfo=0&rel=0';$('iframe',$(this)).attr('data-src',videosrc);}
let autoplay=$('iframe',$(this)).data('src');$('iframe',$(this)).attr('src',autoplay);$('iframe',$(this)).attr('loading','lazy');}).on('hide.bs.modal','.video-modal',function(e){$('iframe',$(this)).attr('src','');});let reviews=$('.reviews');if($(reviews).length){$(reviews).each(function(){const module=$('#'+$(this).attr('id'));const display_as=$(module).data('display');const testimonials=$('.testimonials',$(module));function reviewSlideshow(show,options){if(options===undefined){options={arrows:true,dots:true,draggable:true,swipe:true,swipeToSlide:true,touchMove:true,draggable:true,accessibility:true,adaptiveHeight:true,prevArrow:'',nextArrow:'<button class="arrow" type="button" role="button" aria-label="Next"></button>',rtl:($('html').attr('dir')==='rtl'?true:false)};}
if(show===true){$(testimonials).not('.slick-initialized').slick(options);}else{$(testimonials).slick('unslick');}}
if(display_as==='rows'){enquire.register("screen and (max-width: 767.980px)",{match:function(){reviewSlideshow(true);},unmatch:function(){reviewSlideshow(false);}});}else if(display_as==='slides'){reviewSlideshow(true,{arrows:false,dots:true,draggable:true,swipe:true,swipeToSlide:true,touchMove:true,draggable:true,accessibility:true,adaptiveHeight:false,prevArrow:'',nextArrow:'',infinite:true,rtl:($('html').attr('dir')==='rtl'?true:false),slidesToShow:2,slidesToScroll:2,responsive:[{breakpoint:767,settings:{slidesToShow:1,slidesToScroll:1}}]});}
$(testimonials).on('swipe',function(event,slick,direction){let swiped=direction.charAt(0).toUpperCase()+direction.slice(1);gu_fire_event('Testimonials','Swipe'+swiped,'s4');});});};let stock_widget=$('#check-stock[data-page]');if($(stock_widget).length){let bar=$('.progress-bar',$(stock_widget));let heading=$('.progress-msg',$(stock_widget));let sw_milestones=JSON.parse(String($(stock_widget).data('milestones')).replace(/'/g,'"'));let sw_speed=$(stock_widget).data('speed');let sw_display_at_load=$(stock_widget).data('display-at-load');let sw_page=$(stock_widget).data('page');function checkStock(targetUrl){$('body').addClass('stock-widget-shown');sw_milestones.sort((a,b)=>(a.threshold<b.threshold)?-1:1);$('span',$(bar)).css({'background':sw_milestones[0].bg_color,'color':sw_milestones[0].txt_color});let int=0;let progress=setInterval(function(){progressBar(targetUrl);},((sw_speed-1)*10));function progressBar(targetUrl){if(int>=100){$('span',$(bar)).css('width','100%').attr('data-percent','100%');clearInterval(progress);if(targetUrl!==''){console.log('Redirect:',targetUrl);window.location.href=targetUrl;}else{$(stock_widget).modal('hide');$('body').removeClass('stock-widget-shown');}}else{let msg,bg_color,txt_color;for(let k=0;k<sw_milestones.length;k++){if(int<sw_milestones[k].threshold){break;}
msg=sw_milestones[k].msg;bg_color=sw_milestones[k].bg_color;txt_color=sw_milestones[k].txt_color;}
$(heading).text(msg);$('span',$(bar)).css({'width':int+'%','background':bg_color,'color':txt_color}).attr('data-percent',int+'%');int++;if(int>=96){clearInterval(progress);progress=setInterval(function(){progressBar(targetUrl);},250);}}}}
function displayWidget(targetUrl){$(stock_widget).on('show.bs.modal',function(e){checkStock(targetUrl);});$(stock_widget).modal({backdrop:'static',show:true,focus:true,keyboard:false});}
function initSetup(){if(sw_display_at_load==='true'||sw_page==='offer'){displayWidget('');}else{$('a[href]').each(function(){const href=$(this).attr('href');if(!~href.indexOf('#faq')){$(this).attr('data-check-stock',href).attr('href','#');}});}}
initSetup();$(document).on('click','[data-check-stock]',function(e){e.preventDefault();let targetUrl=$(this).attr('data-check-stock');displayWidget(targetUrl);});}});});